name: Build Docker image

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: [ 'go' ]
        # Learn more...
    container:
      image: golang
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install & Tests
        run: |
          go mod download
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          # Must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head of the pull request.
          # Only include this option if you are running this workflow on pull requests.
          fetch-depth: 2

      # If this run was triggered by a pull request event then checkout
      # the head of the pull request instead of the merge commit.
      # Only include this step if you are running this workflow on pull requests.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Set up CD
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Qemu
        uses: docker/setup-qemu-action@v1.2.0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1.5.0
      - name: Docker login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: |
            adrianvillanueva997/geofenceapi:${{ github.sha }}
            adrianvillanueva997/geofenceapi:latest