name: Build Docker image

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, closed ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Override automatic language detection by changing the below list
        # Supported options are ['csharp', 'cpp', 'go', 'java', 'javascript', 'python']
        language: [ 'go' ]
        # Learn more...
    container:
      image: golang
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install & Tests
        run: |
          go mod download
  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build
        run: docker build -t api .